// <auto-generated />
using System;
using Keuangan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Keuangan.Data.Migrations
{
    [DbContext(typeof(KeuanganDbContext))]
    [Migration("20260930033435_TambahPenggajian")]
    partial class TambahPenggajian
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Keuangan.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterDataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeDataJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AuditCode")
                        .IsUnique();

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.ChartOfAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NormalBalance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChartOfAccounts");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.DocumentNumberFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DigitPadding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResetCadence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentNumberFormats");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.DocumentSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocType", "PeriodKey")
                        .IsUnique();

                    b.ToTable("DocumentSequences");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKepalaSekolah")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jabatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Katalog")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pendidikan")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusKeluar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HubId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoTagihSaatDaftar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CicilanJumlahBulanDefault")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CicilanMinimalPerBulan")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Frekuensi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kategori")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioritas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesAngkatanRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeeCode")
                        .IsUnique();

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FeeTypeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Angkatan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BerlakuMulai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId", "Angkatan", "BerlakuMulai")
                        .IsUnique();

                    b.ToTable("FeeTypeRates");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderNote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TxCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TxDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TxType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TxCode")
                        .IsUnique();

                    b.HasIndex("TxDate");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Memo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("EntryNo")
                        .IsUnique();

                    b.HasIndex("SourceTransactionId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.JournalLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Credit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Debit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalLines");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagihanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("PaymentCode")
                        .IsUnique();

                    b.HasIndex("PaymentDate");

                    b.HasIndex("StudentId");

                    b.HasIndex("TagihanId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PaymentReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReferenceNo")
                        .IsUnique();

                    b.ToTable("PaymentReferences");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PayrollComponentGroups");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId", "EducationLevel")
                        .IsUnique();

                    b.ToTable("PayrollComponentRates");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalcMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRate")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("EditRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KelompokPajakBpjs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QtyLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlipSection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("PayrollComponentTypes");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BiayaJabatan")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HariMasuk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keterangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PajakDitanggungPemerintah")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PtkpWajibPajak")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("PayrollPeriodId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PayrollItems");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollItemLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayrollItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("PayrollItemId", "ComponentTypeId")
                        .IsUnique();

                    b.ToTable("PayrollItemLines");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodKey")
                        .IsUnique();

                    b.ToTable("PayrollPeriods");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateComponentBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("LineId");

                    b.ToTable("PayslipTemplateComponentBindings");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Indent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListKelompokPajakBpjs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListSlipSection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Urutan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PayslipTemplateLines");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateSumBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sign")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceLineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.HasIndex("SourceLineId");

                    b.ToTable("PayslipTemplateSumBindings");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PeriodClosing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClosedByRole")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JournalEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExpense")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId");

                    b.HasIndex("PeriodKey")
                        .IsUnique();

                    b.ToTable("PeriodClosings");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.RecurringBillingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeriodLabel")
                        .IsUnique();

                    b.ToTable("RecurringBillingRuns");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.SalarySlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PayrollItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlipNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayrollItemId")
                        .IsUnique();

                    b.HasIndex("SlipNo")
                        .IsUnique();

                    b.ToTable("SalarySlips");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Angkatan")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Katalog")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SemesterTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tingkat")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HubId")
                        .IsUnique();

                    b.HasIndex("Nis");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("VaNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.StudentFeeSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OverrideAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("StudentId", "FeeTypeId")
                        .IsUnique();

                    b.ToTable("StudentFeeSubscriptions");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.StudentVirtualAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("VaNumber")
                        .IsUnique();

                    b.ToTable("StudentVirtualAccounts");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Tagihan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CicilanDari")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CicilanKe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagihanCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("FeeTypeId");

                    b.HasIndex("LastPaymentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TagihanCode")
                        .IsUnique();

                    b.ToTable("TagihanList");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodeHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FeeTypeRate", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.FeeType", "FeeType")
                        .WithMany("Rates")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Keuangan.Data.Entities.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Keuangan.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("FeeType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.JournalEntry", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.FinancialTransaction", "SourceTransaction")
                        .WithMany("JournalEntries")
                        .HasForeignKey("SourceTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceTransaction");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.JournalLine", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.ChartOfAccount", "Account")
                        .WithMany("JournalLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Payment", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.Tagihan", "Tagihan")
                        .WithMany("PaymentsApplied")
                        .HasForeignKey("TagihanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Keuangan.Data.Entities.FinancialTransaction", "Transaction")
                        .WithMany("Payments")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeeType");

                    b.Navigation("Student");

                    b.Navigation("Tagihan");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PaymentReference", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.Payment", "Payment")
                        .WithMany("References")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentRate", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayrollComponentType", "ComponentType")
                        .WithMany("Rates")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentType", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayrollComponentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollItem", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.PayrollPeriod", "PayrollPeriod")
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.FinancialTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollItemLine", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayrollComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.PayrollItem", "PayrollItem")
                        .WithMany("Lines")
                        .HasForeignKey("PayrollItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("PayrollItem");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateComponentBinding", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayrollComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.PayslipTemplateLine", "Line")
                        .WithMany("ComponentBindings")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateSumBinding", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayslipTemplateLine", "Line")
                        .WithMany("SumBindings")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.PayslipTemplateLine", "SourceLine")
                        .WithMany()
                        .HasForeignKey("SourceLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");

                    b.Navigation("SourceLine");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PeriodClosing", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.JournalEntry", "JournalEntry")
                        .WithMany()
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.SalarySlip", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.PayrollItem", "PayrollItem")
                        .WithOne("Slip")
                        .HasForeignKey("Keuangan.Data.Entities.SalarySlip", "PayrollItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayrollItem");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.StudentFeeSubscription", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.FeeType", "FeeType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.Student", "Student")
                        .WithMany("FeeSubscriptions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeeType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.StudentVirtualAccount", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.Student", "Student")
                        .WithMany("VirtualAccounts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Tagihan", b =>
                {
                    b.HasOne("Keuangan.Data.Entities.FeeType", "FeeType")
                        .WithMany()
                        .HasForeignKey("FeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Keuangan.Data.Entities.Payment", "LastPayment")
                        .WithMany()
                        .HasForeignKey("LastPaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Keuangan.Data.Entities.Student", "Student")
                        .WithMany("TagihanList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeeType");

                    b.Navigation("LastPayment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.ChartOfAccount", b =>
                {
                    b.Navigation("JournalLines");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FeeType", b =>
                {
                    b.Navigation("Rates");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.FinancialTransaction", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.JournalEntry", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Payment", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollComponentType", b =>
                {
                    b.Navigation("Rates");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayrollItem", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Slip");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.PayslipTemplateLine", b =>
                {
                    b.Navigation("ComponentBindings");

                    b.Navigation("SumBindings");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Student", b =>
                {
                    b.Navigation("FeeSubscriptions");

                    b.Navigation("TagihanList");

                    b.Navigation("VirtualAccounts");
                });

            modelBuilder.Entity("Keuangan.Data.Entities.Tagihan", b =>
                {
                    b.Navigation("PaymentsApplied");
                });
#pragma warning restore 612, 618
        }
    }
}
